### PR TITLE
Remove get_fee() and use 1 sat/byte default fee

### PR DESCRIPTION
**Pull request by merc1er**
Solves #66

### CODE REVIEW

**Comment by merc1er** [comment]
One of the tests fails because the livecoin API is down (apparently hacked?):
Screenshot 2021-01-24 at 02 27 44

**Review by teran-mckinney — APPROVED** [review]
Looks good to me! Nice change. Approved.

**Comment by teran-mckinney** [comment]
If Livecoin is hacked, maybe we should remove it before the next release.

**Comment by merc1er** [comment]
> If Livecoin is hacked, maybe we should remove it before the next release.

Yes, it also looks like it's staged. Either way, I'll prepare an other PR removing it.

**Pull request merged**
