### PR TITLE
requirements-dev

### PR DESCRIPTION
**Pull request by PiRK**
I created a requirements-dev.txt file, to simplify the setup for contributors to the project.

It allows installing everything needed (tests, doc, extras_require) in a single command:

`pip install -r requirements-dev.txt`

### CODE REVIEW

**Comment by PiRK** [comment]
The first commit is a bit messy and contained unneeded stuff. This is because I copied the file over from another project (https://github.com/silx-kit/silx/blob/master/requirements-dev.txt)

**Review by merc1er — APPROVED** [review]
Looks good to me, thank you!

**Comment by merc1er** [comment]
@teran-mckinney what do you think?

**Review by teran-mckinney — APPROVED** [review]
Looks great, thank you! Sorry for the wait, was out of town.

**Pull request merged**
