### PR TITLE
Add support for Cashaddress URI

### PR DESCRIPTION
**Pull request by yashasvi-ranawat**
Adds support for parsing and generating CashAddress URIs.

### CODE REVIEW

**Review by merc1er — CHANGES_REQUESTED** [review]
Good work! Sorry for taking so long to review this!

This seems to not be directly related to BitCash's core functionality (creating a wallet and sending coins), but I think it is good to have utils around addresses.

Documentation is missing though. Would you be able to write it? This feature without documentation wouldn't be very useful.
I am happy to merge this and release an update as soon as you add the documentation 🙂

Edit: ah there also seems to be a merge conflict.

**Comment by yashasvi-ranawat** [comment]
I simplified the uri parsing and generation, uses urllib which makes it quite robust.

I added some simple documentation in dev guides. Is there any other place the documentation should be added?

PS: This also adds the cashaddress class Address, although that doesn't have any docs. I think I'd leave it at that, and wait for cashtokens merge. Otherwise the rebase will be quite messy.

**Comment by merc1er** [comment]
> I added some simple documentation in dev guides. Is there any other place the documentation should be added?

I think that should do. I will build the site and see if that's enough.

**Comment by merc1er** [comment]
Seems like there's only one mention of URI in the changelog:

cl

It should probably have its own short page with a couple examples, a bit like this: https://bitcash.dev/guide/keys.html#formats.

**Pull request merged**
