### PR TITLE
Adds P2SH32 output support

### PR DESCRIPTION
**Pull request by yashasvi-ranawat**
P2SH32 is being worked on for May 2023 upgrade. This PR adds P2SH32 output support.

TODO:

- [x] [Check if OP_Hash256 or OP_SHA256 is used for hashing. ](https://bitcoincashresearch.org/t/chip-2022-05-pay-to-script-hash-32-p2sh32-for-bitcoin-cash/806/3)
- [x] Add test for P2SH32 output.

### CODE REVIEW

**Comment by A60AB5450353F40E** [comment]
@yashasvi-ranawat it's OP_HASH256

Here's the CHIP/spec: https://gitlab.com/0353F40E/p2sh32/-/blob/main/CHIP-2022-05_Pay-to-Script-Hash-32_(P2SH32)_for_Bitcoin_Cash.md#consensus-rules

**Comment by yashasvi-ranawat** [comment]
@merc1er its ready for review.

**Comment by merc1er** [comment]
> @merc1er its ready for review.

Ok, I will try to review this next week. Thank you!

**Review by merc1er — COMMENTED** [review]
Is this PR still needed?

**Comment by yashasvi-ranawat** [comment]
#122 already incorporates these changes.

**Pull request closed without merging**
